# Atelier NumPy — Analyse de données de capteurs IoT

**Auteur :** Khadija NGOM

**Objectif :** préparer et analyser les données de capteurs (température, humidité, pression, consommation) en vue d'un futur système de détection d'anomalies par Machine Learning.

In [3]:
import numpy as np

## Partie 1 — Listes Python vs tableaux NumPy

**Énoncé** — on dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0, 25.8.
1. Créer une liste Python stockant ces températures.
2. Créer un tableau NumPy équivalent.
3. Effectuer une multiplication par 2 sur ces deux collections.
4. Quelle différence observe-t-on ?

### Concept : créer un tableau NumPy à partir d'une liste
- **Objectif :** transformer une liste Python en tableau NumPy pour faire des calculs directement sur toutes les valeurs.
- **Syntaxe :** `np.array(une_liste)`
- **Exemple :** voir les cellules ci-dessous.

In [4]:
# Q1 : la liste Python
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]

# Q2 : le tableau NumPy equivalent
temperatures_array = np.array(temperatures_liste)

print(temperatures_liste)
print(temperatures_array)

[24.5, 25.1, 26.3, 27.0, 25.8]
[24.5 25.1 26.3 27.  25.8]


In [5]:
# Q3 : multiplication par 2 des deux collections
print(temperatures_liste * 2)
print(temperatures_array * 2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


**Q4 — différence observée :**
- Sur une liste Python, `* 2` répète les éléments : la liste passe de 5 à 10 valeurs.
- Sur un tableau NumPy, `* 2` multiplie chaque valeur par 2 : on garde 5 valeurs, chacune doublée.

NumPy applique donc l'opération à toutes les valeurs d'un coup : c'est la **vectorisation**, son principal atout.

## Partie 2 — Création des données

**Énoncé**
1. Créer un tableau de température de 10 capteurs, initialement à zéro.
2. Créer un tableau de 10 valeurs égales à 1.
3. Créer un tableau de 10 valeurs égales à 25.
4. Créer une matrice identité de taille 5 × 5.
5. Créer les 24 heures (de 0 à 23) d'une journée.
6. Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C.
7. Créer aléatoirement les températures de 100 mesures, de façon reproductible.

### Concepts (questions 1 à 4)
- **`np.zeros(n)`** — tableau de `n` zéros.
- **`np.ones(n)`** — tableau de `n` uns.
- **`np.full(n, valeur)`** — tableau de `n` fois la même valeur.
- **`np.eye(taille)`** — matrice identité (carrée, des 1 sur la diagonale, des 0 ailleurs).

### Concepts (questions 5 à 7)
- **`np.arange(fin)`** — suite d'entiers de 0 à `fin` exclu.
- **`np.linspace(debut, fin, n)`** — `n` valeurs régulièrement espacées entre `debut` et `fin` (bornes comprises).
- **`np.random.seed(42)` puis `np.random.uniform(min, max, n)`** — `n` valeurs aléatoires reproductibles (la graine fixe le hasard).

In [6]:
# Q1 : 10 capteurs a zero
capteurs_zero = np.zeros(10)
print(capteurs_zero)

# Q2 : 10 valeurs egales a 1
capteurs_un = np.ones(10)
print(capteurs_un)

# Q3 : 10 valeurs egales a 25
capteurs_25 = np.full(10, 25)
print(capteurs_25)

# Q4 : matrice identite 5x5
identite = np.eye(5)
print(identite)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[25 25 25 25 25 25 25 25 25 25]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# Q5 : les 24 heures (0 a 23)
heures = np.arange(24)
print(heures)

# Q6 : 10 valeurs entre 20 et 30
temperatures_lin = np.linspace(20, 30, 10)
print(temperatures_lin)

# Q7 : 100 mesures aleatoires reproductibles
np.random.seed(42)
mesures_alea = np.random.uniform(20, 30, 100)
print(mesures_alea)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21

## Partie 3 — Exploration des tableaux

**Énoncé**
1. Créer aléatoirement un tableau des 24 températures d'une journée.
2. Déterminer : a) le nombre de dimensions, b) le nombre de valeurs, c) le type des données, d) la forme du tableau.

### Concepts
- **`.ndim`** — nombre de dimensions du tableau.
- **`.size`** — nombre total de valeurs.
- **`.dtype`** — type des données.
- **`.shape`** — forme du tableau (dimensions détaillées).

In [8]:
# Q1 : 24 températures aléatoires (reproductibles) entre 20 et 30
np.random.seed(0)
temperatures_jour = np.random.uniform(20, 30, 24)
print(temperatures_jour)

# Q2a : nombre de dimensions
print(temperatures_jour.ndim)

# Q2b : nombre de valeurs
print(temperatures_jour.size)

# Q2c : type des données
print(temperatures_jour.dtype)

# Q2d : forme du tableau
print(temperatures_jour.shape)

[25.48813504 27.15189366 26.02763376 25.44883183 24.23654799 26.45894113
 24.37587211 28.91773001 29.63662761 23.83441519 27.91725038 25.2889492
 25.68044561 29.25596638 20.71036058 20.871293   20.20218397 28.32619846
 27.78156751 28.70012148 29.78618342 27.99158564 24.61479362 27.80529176]
1
24
float64
(24,)


## Partie 4 — Indexation et slicing

**Énoncé** — à partir du tableau des 24 températures, afficher :
1. la première mesure
2. la dernière mesure
3. la température de 8h
4. les températures de 8h à 12h
5. les températures des 6 premières heures
6. les températures des heures paires

### Concepts
- **Indexation** `tableau[i]` — une valeur à la position `i` (on compte à partir de 0).
- **Indice négatif** `tableau[-1]` — la dernière valeur.
- **Slicing** `tableau[début:fin]` — une tranche (fin exclue).
- **Pas** `tableau[début:fin:pas]` — un élément tous les `pas`.

In [9]:
# Q1 : première mesure
print(temperatures_jour[0])

# Q2 : dernière mesure
print(temperatures_jour[-1])

# Q3 : température de 8h
print(temperatures_jour[8])

# Q4 : températures de 8h à 12h
print(temperatures_jour[8:12])

# Q5 : les 6 premières heures
print(temperatures_jour[:6])

# Q6 : les heures paires
print(temperatures_jour[::2])

25.488135039273246
27.805291762864556
29.636627605010293
[29.63662761 23.83441519 27.91725038 25.2889492 ]
[25.48813504 27.15189366 26.02763376 25.44883183 24.23654799 26.45894113]
[25.48813504 26.02763376 24.23654799 24.37587211 29.63662761 27.91725038
 25.68044561 20.71036058 20.20218397 27.78156751 29.78618342 24.61479362]
