# Atelier NumPy — Analyse de données de capteurs IoT

**Auteur :** Khadija NGOM

**Objectif :** préparer et analyser les données de capteurs (température, humidité, pression, consommation) en vue d'un futur système de détection d'anomalies par Machine Learning.

In [3]:
import numpy as np

## Partie 1 — Listes Python vs tableaux NumPy

**Énoncé** — on dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0, 25.8.
1. Créer une liste Python stockant ces températures.
2. Créer un tableau NumPy équivalent.
3. Effectuer une multiplication par 2 sur ces deux collections.
4. Quelle différence observe-t-on ?

### Concept : créer un tableau NumPy à partir d'une liste
- **Objectif :** transformer une liste Python en tableau NumPy pour faire des calculs directement sur toutes les valeurs.
- **Syntaxe :** `np.array(une_liste)`
- **Exemple :** voir les cellules ci-dessous.

In [4]:
# Q1 : la liste Python
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]

# Q2 : le tableau NumPy equivalent
temperatures_array = np.array(temperatures_liste)

print(temperatures_liste)
print(temperatures_array)

[24.5, 25.1, 26.3, 27.0, 25.8]
[24.5 25.1 26.3 27.  25.8]


In [5]:
# Q3 : multiplication par 2 des deux collections
print(temperatures_liste * 2)
print(temperatures_array * 2)

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
[49.  50.2 52.6 54.  51.6]


**Q4 — différence observée :**
- Sur une liste Python, `* 2` répète les éléments : la liste passe de 5 à 10 valeurs.
- Sur un tableau NumPy, `* 2` multiplie chaque valeur par 2 : on garde 5 valeurs, chacune doublée.

NumPy applique donc l'opération à toutes les valeurs d'un coup : c'est la **vectorisation**, son principal atout.

## Partie 2 — Création des données

**Énoncé**
1. Créer un tableau de température de 10 capteurs, initialement à zéro.
2. Créer un tableau de 10 valeurs égales à 1.
3. Créer un tableau de 10 valeurs égales à 25.
4. Créer une matrice identité de taille 5 × 5.
5. Créer les 24 heures (de 0 à 23) d'une journée.
6. Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C.
7. Créer aléatoirement les températures de 100 mesures, de façon reproductible.

### Concepts (questions 1 à 4)
- **`np.zeros(n)`** — tableau de `n` zéros.
- **`np.ones(n)`** — tableau de `n` uns.
- **`np.full(n, valeur)`** — tableau de `n` fois la même valeur.
- **`np.eye(taille)`** — matrice identité (carrée, des 1 sur la diagonale, des 0 ailleurs).

### Concepts (questions 5 à 7)
- **`np.arange(fin)`** — suite d'entiers de 0 à `fin` exclu.
- **`np.linspace(debut, fin, n)`** — `n` valeurs régulièrement espacées entre `debut` et `fin` (bornes comprises).
- **`np.random.seed(42)` puis `np.random.uniform(min, max, n)`** — `n` valeurs aléatoires reproductibles (la graine fixe le hasard).

In [6]:
# Q1 : 10 capteurs a zero
capteurs_zero = np.zeros(10)
print(capteurs_zero)

# Q2 : 10 valeurs egales a 1
capteurs_un = np.ones(10)
print(capteurs_un)

# Q3 : 10 valeurs egales a 25
capteurs_25 = np.full(10, 25)
print(capteurs_25)

# Q4 : matrice identite 5x5
identite = np.eye(5)
print(identite)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[25 25 25 25 25 25 25 25 25 25]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# Q5 : les 24 heures (0 a 23)
heures = np.arange(24)
print(heures)

# Q6 : 10 valeurs entre 20 et 30
temperatures_lin = np.linspace(20, 30, 10)
print(temperatures_lin)

# Q7 : 100 mesures aleatoires reproductibles
np.random.seed(42)
mesures_alea = np.random.uniform(20, 30, 100)
print(mesures_alea)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]
[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21

## Partie 3 — Exploration des tableaux

**Énoncé**
1. Créer aléatoirement un tableau des 24 températures d'une journée.
2. Déterminer : a) le nombre de dimensions, b) le nombre de valeurs, c) le type des données, d) la forme du tableau.

### Concepts
- **`.ndim`** — nombre de dimensions du tableau.
- **`.size`** — nombre total de valeurs.
- **`.dtype`** — type des données.
- **`.shape`** — forme du tableau (dimensions détaillées).

In [8]:
# Q1 : 24 températures aléatoires (reproductibles) entre 20 et 30
np.random.seed(0)
temperatures_jour = np.random.uniform(20, 30, 24)
print(temperatures_jour)

# Q2a : nombre de dimensions
print(temperatures_jour.ndim)

# Q2b : nombre de valeurs
print(temperatures_jour.size)

# Q2c : type des données
print(temperatures_jour.dtype)

# Q2d : forme du tableau
print(temperatures_jour.shape)

[25.48813504 27.15189366 26.02763376 25.44883183 24.23654799 26.45894113
 24.37587211 28.91773001 29.63662761 23.83441519 27.91725038 25.2889492
 25.68044561 29.25596638 20.71036058 20.871293   20.20218397 28.32619846
 27.78156751 28.70012148 29.78618342 27.99158564 24.61479362 27.80529176]
1
24
float64
(24,)


## Partie 4 — Indexation et slicing

**Énoncé** — à partir du tableau des 24 températures, afficher :
1. la première mesure
2. la dernière mesure
3. la température de 8h
4. les températures de 8h à 12h
5. les températures des 6 premières heures
6. les températures des heures paires

### Concepts
- **Indexation** `tableau[i]` — une valeur à la position `i` (on compte à partir de 0).
- **Indice négatif** `tableau[-1]` — la dernière valeur.
- **Slicing** `tableau[début:fin]` — une tranche (fin exclue).
- **Pas** `tableau[début:fin:pas]` — un élément tous les `pas`.

In [9]:
# Q1 : première mesure
print(temperatures_jour[0])

# Q2 : dernière mesure
print(temperatures_jour[-1])

# Q3 : température de 8h
print(temperatures_jour[8])

# Q4 : températures de 8h à 12h
print(temperatures_jour[8:12])

# Q5 : les 6 premières heures
print(temperatures_jour[:6])

# Q6 : les heures paires
print(temperatures_jour[::2])

25.488135039273246
27.805291762864556
29.636627605010293
[29.63662761 23.83441519 27.91725038 25.2889492 ]
[25.48813504 27.15189366 26.02763376 25.44883183 24.23654799 26.45894113]
[25.48813504 26.02763376 24.23654799 24.37587211 29.63662761 27.91725038
 25.68044561 20.71036058 20.20218397 27.78156751 29.78618342 24.61479362]


## Partie 5 — Filtrage booléen

**Énoncé** — à partir du tableau des 24 températures :
1. Afficher les températures supérieures à 30 °C.
2. Afficher les températures « normales » (entre 20 et 30 °C).
3. Créer `anomalies`, tableau booléen des températures > 35 °C.
4. Déterminer le nombre de températures anormales à l'aide de `anomalies`.

### Concepts
- **Masque booléen** `tableau > valeur` — renvoie un tableau de True/False.
- **Filtrage** `tableau[condition]` — garde les valeurs où la condition est vraie.
- **Combiner** `(cond1) & (cond2)` — ET ; `(cond1) | (cond2)` — OU (parenthèses obligatoires).
- **Compter les True** `np.sum(masque)` — additionne les True (True=1, False=0).

In [ ]:
# Q1 : températures supérieures à 30°C
print(temperatures_jour[temperatures_jour > 30])
# Q2 : températures normales (entre 20 et 30°C)
print(temperatures_jour[(temperatures_jour >= 20) & (temperatures_jour <= 30)])
# Q3 : tableau booléen des anomalies (> 35°C)
anomalies = temperatures_jour > 35
print(anomalies)
# Q4 : nombre de températures anormales
print(np.sum(anomalies))

# Test : on force une anomalie pour vérifier comment le code reagit
temperatures_test = temperatures_jour.copy()   # une copie pour ne pas toucher l'original
temperatures_test[5] = 38.0                     # on met 38°C à l'index 5

anomalies_test = temperatures_test > 35
print(anomalies_test)              # un seul True
print(np.sum(anomalies_test))      # affiche 1

[]
[25.48813504 27.15189366 26.02763376 25.44883183 24.23654799 26.45894113
 24.37587211 28.91773001 29.63662761 23.83441519 27.91725038 25.2889492
 25.68044561 29.25596638 20.71036058 20.871293   20.20218397 28.32619846
 27.78156751 28.70012148 29.78618342 27.99158564 24.61479362 27.80529176]
[False False False False False False False False False False False False
 False False False False False False False False False False False False]
0
[False False False False False  True False False False False False False
 False False False False False False False False False False False False]
1


## Partie 6 — Manipulation des dimensions

**Énoncé** — on suppose 5 capteurs mesurant sur 24 heures.
1. Créer aléatoirement la matrice des températures (5 capteurs × 24 heures).
2. Transformer la matrice en tableau unidimensionnel.
3. Déterminer la transposée de la matrice.
4. Extraire toutes les mesures du capteur 1.
5. Extraire toutes les mesures du capteur 5.
6. Extraire les mesures de tous les capteurs à 10h.
7. Extraire les mesures des capteurs 2 à 4 entre 8h et 12h.

### Concepts
- **Matrice aléatoire** `np.random.uniform(min, max, (lignes, colonnes))`.
- **Aplatir** `matrice.flatten()` — repasse en une seule dimension.
- **Transposer** `matrice.T` — échange lignes et colonnes.
- **Indexation 2D** `matrice[ligne, colonne]`, avec `:` pour « tout ».

In [17]:
# Q1 : matrice 5 capteurs x 24 heures
np.random.seed(1)
matrice = np.random.uniform(20, 30, (5, 24))
print("Forme :", matrice.shape)
print(matrice)

Forme : (5, 24)
[[24.17022005 27.20324493 20.00114375 23.02332573 21.46755891 20.92338595
  21.86260211 23.45560727 23.96767474 25.38816734 24.19194514 26.852195
  22.0445225  28.78117436 20.27387593 26.7046751  24.17304802 25.58689828
  21.40386939 21.98101489 28.00744569 29.68261576 23.13424178 26.92322616]
 [28.76389152 28.94606664 20.85044211 20.39054783 21.6983042  28.78142503
  20.98346834 24.21107625 29.5788953  25.33165285 26.91877114 23.15515631
  26.86500928 28.34625672 20.18288277 27.50144315 29.88861089 27.48165654
  22.80443992 27.89279328 21.03226007 24.47893526 29.08595503 22.93614148]
 [22.87775339 21.30028572 20.19366958 26.78835533 22.11628116 22.65546659
  24.91573159 20.53362545 25.74117605 21.46728575 25.89305537 26.9975836
  21.02334429 24.14055988 26.94400158 24.1417927  20.49953459 25.35896406
  26.63794645 25.14889112 29.44594756 25.86555041 29.03401915 21.37474704]
 [21.39276347 28.07391289 23.97676837 21.65354197 29.2750858  23.4776586
  27.50812103 27.259979

In [18]:
# Q2 : aplatir en une seule dimension
print(matrice.flatten())

[24.17022005 27.20324493 20.00114375 23.02332573 21.46755891 20.92338595
 21.86260211 23.45560727 23.96767474 25.38816734 24.19194514 26.852195
 22.0445225  28.78117436 20.27387593 26.7046751  24.17304802 25.58689828
 21.40386939 21.98101489 28.00744569 29.68261576 23.13424178 26.92322616
 28.76389152 28.94606664 20.85044211 20.39054783 21.6983042  28.78142503
 20.98346834 24.21107625 29.5788953  25.33165285 26.91877114 23.15515631
 26.86500928 28.34625672 20.18288277 27.50144315 29.88861089 27.48165654
 22.80443992 27.89279328 21.03226007 24.47893526 29.08595503 22.93614148
 22.87775339 21.30028572 20.19366958 26.78835533 22.11628116 22.65546659
 24.91573159 20.53362545 25.74117605 21.46728575 25.89305537 26.9975836
 21.02334429 24.14055988 26.94400158 24.1417927  20.49953459 25.35896406
 26.63794645 25.14889112 29.44594756 25.86555041 29.03401915 21.37474704
 21.39276347 28.07391289 23.97676837 21.65354197 29.2750858  23.4776586
 27.50812103 27.25997985 28.83306091 26.23672207 27.509

In [19]:
# Q3 : transposee (devient 24 x 5)
print("Forme transposee :", matrice.T.shape)
print(matrice.T)

Forme transposee : (24, 5)
[[24.17022005 28.76389152 22.87775339 21.39276347 29.03379521]
 [27.20324493 28.94606664 21.30028572 28.07391289 25.73679487]
 [20.00114375 20.85044211 20.19366958 23.97676837 20.02870327]
 [23.02332573 20.39054783 26.78835533 21.65354197 26.17144914]
 [21.46755891 21.6983042  22.11628116 29.2750858  23.26644902]
 [20.92338595 28.78142503 22.65546659 23.4776586  25.27058102]
 [21.86260211 20.98346834 24.91573159 27.50812103 28.85942099]
 [23.45560727 24.21107625 20.53362545 27.25997985 23.5726976 ]
 [23.96767474 29.5788953  25.74117605 28.83306091 29.08535151]
 [25.38816734 25.33165285 21.46728575 26.23672207 26.23360116]
 [24.19194514 26.91877114 25.89305537 27.50942434 20.15821243]
 [26.852195   23.15515631 26.9975836  23.48898342 29.29437234]
 [22.0445225  26.86500928 21.02334429 22.69927892 26.90896918]
 [28.78117436 28.34625672 24.14055988 28.95886218 29.9732285 ]
 [20.27387593 20.18288277 26.94400158 24.2809119  21.72340508]
 [26.7046751  27.50144315 24

In [20]:
# Q4 : capteur 1 -> ligne d'index 0
print(matrice[0, :])
# Q5 : capteur 5 -> ligne d'index 4
print(matrice[4, :])
# Q6 : tous les capteurs a 10h -> colonne d'index 10
print(matrice[:, 10])
# Q7 : capteurs 2 a 4 (index 1 a 3) entre 8h et 12h (colonnes 8 a 11)
print(matrice[1:4, 8:12])

[24.17022005 27.20324493 20.00114375 23.02332573 21.46755891 20.92338595
 21.86260211 23.45560727 23.96767474 25.38816734 24.19194514 26.852195
 22.0445225  28.78117436 20.27387593 26.7046751  24.17304802 25.58689828
 21.40386939 21.98101489 28.00744569 29.68261576 23.13424178 26.92322616]
[29.03379521 25.73679487 20.02870327 26.17144914 23.26644902 25.27058102
 28.85942099 23.5726976  29.08535151 26.23360116 20.15821243 29.29437234
 26.90896918 29.9732285  21.72340508 21.3713575  29.32595463 26.96818161
 20.66000173 27.55463053 27.53876188 29.23024536 27.11524759 21.24270962]
[24.19194514 26.91877114 25.89305537 27.50942434 20.15821243]
[[29.5788953  25.33165285 26.91877114 23.15515631]
 [25.74117605 21.46728575 25.89305537 26.9975836 ]
 [28.83306091 26.23672207 27.50942434 23.48898342]]


## Partie 7 — Concaténation

**Énoncé** — un 2nd bâtiment avec 3 capteurs.
1. Matrice aléatoire des 3 capteurs sur une journée (3 × 24).
2. Fusionner les 8 capteurs (5 + 3) de deux manières différentes → matrice 8 × 24.

### Concepts
- `np.vstack([a, b])` — empile verticalement (l'une sous l'autre).
- `np.concatenate([a, b], axis=0)` — concatène selon les lignes (axis=0 = vertical).

In [22]:
# Q1 : 2nd batiment, 3 capteurs x 24 heures
np.random.seed(2)
batiment2 = np.random.uniform(20, 30, (3, 24))
print("Forme batiment 2 :", batiment2.shape)

# batiment 1 = la matrice de la Partie 6 (5 x 24)
batiment1 = matrice

# Q2 - methode 1 : vstack
fusion_v1 = np.vstack([batiment1, batiment2])
print("Fusion methode 1 (vstack) :", fusion_v1.shape)

# Q2 - methode 2 : concatenate axis=0
fusion_v2 = np.concatenate([batiment1, batiment2], axis=0)
print("Fusion methode 2 (concatenate) :", fusion_v2.shape)

# verification : les deux methodes donnent le meme resultat
print("Resultats identiques :", np.array_equal(fusion_v1, fusion_v2))

Forme batiment 2 : (3, 24)
Fusion methode 1 (vstack) : (8, 24)
Fusion methode 2 (concatenate) : (8, 24)
Resultats identiques : True


## Partie 8 — Calcul scientifique

**Énoncé** — sur le tableau des 24 températures du 1er bâtiment (`temperatures_jour`) :
1. min, max, somme, moyenne, médiane, variance, écart-type.
2. Standardiser, puis vérifier moyenne (≈ 0) et écart-type (≈ 1).
3. Normaliser (Min-Max), puis vérifier (valeurs entre 0 et 1).
4. Convertir en Fahrenheit.

### Concepts
- `np.min`, `np.max`, `np.sum`, `np.mean`, `np.median`, `np.var`, `np.std`.
- **Standardisation** : `(x - moyenne) / ecart_type` → moyenne 0, écart-type 1.
- **Normalisation Min-Max** : `(x - min) / (max - min)` → valeurs entre 0 et 1.
- **Fahrenheit** : `x * 9/5 + 32`.

In [23]:
# Q1 : statistiques descriptives
print("min      :", np.min(temperatures_jour))
print("max      :", np.max(temperatures_jour))
print("somme    :", np.sum(temperatures_jour))
print("moyenne  :", np.mean(temperatures_jour))
print("mediane  :", np.median(temperatures_jour))
print("variance :", np.var(temperatures_jour))
print("ecart-type:", np.std(temperatures_jour))

min      : 20.20218397440326
max      : 29.78618342232764
somme    : 626.5088193544082
moyenne  : 26.104534139767008
mediane  : 26.2432874456915
variance : 7.339836759378865
ecart-type: 2.7092133100549436


In [24]:
# Q2 : standardisation
temp_std = (temperatures_jour - np.mean(temperatures_jour)) / np.std(temperatures_jour)
print("Tableau standardise :", temp_std)
print("Moyenne apres standardisation :", np.round(np.mean(temp_std), 6))
print("Ecart-type apres standardisation :", np.round(np.std(temp_std), 6))

Tableau standardise : [-0.22751959  0.38659175 -0.02838476 -0.24202683 -0.68949394  0.13081546
 -0.63806789  1.03838109  1.30373399 -0.83792551  0.66909321 -0.30104124
 -0.15653567  1.1632278  -1.99104793 -1.93164603 -2.17862143  0.82004038
  0.6190112   0.95805942  1.35893666  0.69653116 -0.54987937  0.62776807]
Moyenne apres standardisation : 0.0
Ecart-type apres standardisation : 1.0


In [25]:
# Q3 : normalisation Min-Max
temp_norm = (temperatures_jour - np.min(temperatures_jour)) / (np.max(temperatures_jour) - np.min(temperatures_jour))
print("Tableau normalise :", temp_norm)
print("Min apres normalisation :", np.min(temp_norm))
print("Max apres normalisation :", np.max(temp_norm))

Tableau normalise : [0.55153917 0.7251367  0.60783077 0.54743825 0.42094786 0.65283363
 0.43548501 0.90938507 0.98439526 0.37898909 0.80499445 0.530756
 0.57160496 0.94467685 0.05302344 0.06981522 0.         0.84766433
 0.79083723 0.88667967 1.         0.81275064 0.46041422 0.79331263]
Min apres normalisation : 0.0
Max apres normalisation : 1.0


In [26]:
# Q4 : conversion en Fahrenheit
temp_fahrenheit = temperatures_jour * 9/5 + 32
print(temp_fahrenheit)

[77.87864307 80.87340859 78.84974077 77.80789729 75.62578639 79.62609404
 75.8765698  84.05191401 85.34592969 74.90194734 82.25105069 77.52010856
 78.2248021  84.66073949 69.27864905 69.56832739 68.36393115 82.98715722
 82.00682152 83.66021867 85.61513016 82.38485416 76.30662852 82.04952517]
